version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: password-manager-backend
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: tusharchy/nest-and-postgres-application:latest
    environment:
      - DB_TYPE=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_USER}
      - POSTGRES_SYNC=false
      - POSTGRES_PORT=${POSTGRES_PORT}
      - APP_PORT=${PORT}
    ports:
      - '5000:5000' # expose-to-the-world : only-in-the-docker
    container_name: password-manager-backend
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=masteel.up@bk.ru
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_LISTEN_PORT=5432
    ports:
      - '8080:80'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
volumes:
  pgdata:
  pgadmin-data:
