version: '3.8'
services:
  api:
    # image: nestjs-dockerized
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/DATABASE_URL
      NODE_ENV: development
      PORT: 5000
    ports:
      - '8080:5000'

  postgres:
    image: postgres:lastest
    ports:
      - '35000:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
