version: '3'
services:
  node-admin:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: sh -c "yarn && yarn build && serve -s /app/build"
    ports:
      - '3006:3000'
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=masteel.up@bk.ru
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_LISTEN_PORT=5432
    ports:
      - '8080:80'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
volumes:
  pgdata:
  pgadmin-data:
